stages:
  - build
  - test
  - deploy

variables:
  APP_NAME: nextjs_app
  # Replace <your_ssh_private_key> with the contents of your SSH private key. 
  SSH_PRIVATE_KEY: <your_ssh_private_key>

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build:
  stage: build
  script:
    - npm ci

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    # Replace <your_ssh_user> with your SSH username <your_server_address> with the address of your deployment server.
    # Replace /path/to/deploy/folder with the path to the folder where you want to deploy your Next.js application on the server.
    - ssh <your_ssh_user>@<your_server_address> "cd /path/to/deploy/folder && git pull origin master"
    - ssh <your_ssh_user>@<your_server_address> "cd /path/to/deploy/folder && npm ci && npm run build"

    # this script assumes my server is set-up with necessary infrastructure (e.g., Node.js, Git)

